// export interface ArticlesProps {
//     id:          number;
//     id_category: number;
//     title:       string;
//     description: string;
//     image:       string;
//     url:         string;
//     keywords:    string;
//     status:      number;
//     created_at:  string;
//     updated_at:  string;

//  }

// Generated by https://quicktype.io

export interface ArticlesProps {
    id:          number;
    id_category: number;
    title:       string;
    description: string;
    image:       string;
    url:         string;
    keywords:    string;
    status:      number;
    created_at:  string;
    updated_at:  string;
    category:    Category;
}

export interface Category {
    id:          number;
    category:    string;
    description: null;
    image:       null;
    language:    string;
    created_at:  string;
    updated_at:  string;
}
